# site settings
title: WeSupportJob.com
subtitle: holding hands. 
email: contactus@wesupportjob.com
description: Lear and get the work done at the same time.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://wesupportjob.com # the base hostname & protocol for your site
author:
street_address: 402, Manjeera Plaza, Ameerpet
city: Hyderabad
state: Telangana
zip_code: 500028
country: India
phone: (000) 000-0000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 12

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
